export const studentData = [{"id":1,"name":"Ham Elfitt","age":34,"course":"Luxembourgish"},
{"id":2,"name":"Jordon Rame","age":34,"course":"Dutch"},
{"id":3,"name":"Rosanne Domingues","age":36,"course":"Tamil"},
{"id":4,"name":"Nealon Gorgen","age":28,"course":"Haitian Creole"},
{"id":5,"name":"Karlie Ware","age":26,"course":"Moldovan"},
{"id":6,"name":"Rustin Shulver","age":21,"course":"Bosnian"},
{"id":7,"name":"Magnum Cooper","age":25,"course":"Dari"},
{"id":8,"name":"Camilla Dooler","age":30,"course":"French"},
{"id":9,"name":"Adham Drewry","age":29,"course":"Swahili"},
{"id":10,"name":"Haskel Southway","age":23,"course":"Icelandic"},
{"id":11,"name":"Evered Zolini","age":31,"course":"Chinese"},
{"id":12,"name":"Valentine Judkin","age":50,"course":"Somali"},
{"id":13,"name":"Olympe Tennock","age":43,"course":"Dzongkha"},
{"id":14,"name":"Mel Molloy","age":47,"course":"Amharic"},
{"id":15,"name":"Berkley Guyet","age":48,"course":"Bulgarian"},
{"id":16,"name":"Danya Barnewall","age":45,"course":"Croatian"},
{"id":17,"name":"Krystalle Antham","age":43,"course":"Romanian"},
{"id":18,"name":"Cordelie Wratten","age":32,"course":"Korean"},
{"id":19,"name":"Jere Wheaton","age":32,"course":"Moldovan"},
{"id":20,"name":"Garvey Fessler","age":16,"course":"Zulu"},];